### PR TITLE
Allow per-channel settings

### PR DESCRIPTION
**Pull request by fpoirotte**
This commit makes it possible to get/set a setting for a specific PEAR
channel. This is done by adding a new option to the get/set commands
(-c/--channel) which can be used to pass the name of the PEAR channel
to operate on. Both fullnames (eg. "pear.php.net") and aliases (eg. "pear")
are supported.
See pyrus/Pyrus#7

### CODE REVIEW

**Comment by helgi** [comment]
At a quick glance, looks great. It was one of those things we intended to port over from PEAR, eventually :-)

Would it be possible for you to write tests for this functionality? I can write them as well since writing tests for Pyrus isn't always the most straight forward but it can be based on existing tests or even borrowed from PEAR.

**Comment by fpoirotte** [comment]
yeah, I thought it was lacking tests too, I'll try to write some (or as you suggested, maybe borrow some from PEAR).

**Comment by till** [comment]
Hey @fpoirotte,

can you rebase this? I'll merge ASAP then.

Till

**Comment by fpoirotte** [comment]
Here's a new version of the patch rebased to match pyrus/Pyrus' master branch.
I would have preferred adding this feature another way, maybe using a syntax like: 

```
$config = \Pyrus\Config::current();
$config[ $options['channel'] ]->{$args['variable']} = $args['value'];
```

But the way `\Pyrus\Config` works makes it quite hard (channel-specific settings are keyed based on the attribute's name first, then the channel name).

**Pull request merged**
