### PR TITLE
fix bad package name Pyrus_Developer at "Install developer tools?" 

### PR DESCRIPTION
**Pull request by Tyrael**

### CODE REVIEW

**Comment by helgi** [comment]
This is already fixed, not sure why github says it can be merged: https://github.com/pyrus/Pyrus/blob/master/src/Pyrus/ScriptFrontend/Commands.php#L439

I synced the main pyrus repo with my own where I had done the change a while ago: https://github.com/pyrus/Pyrus/commit/754f1eba6dc219ff766f4fe559624a8edf5c60cc#src/Pyrus/ScriptFrontend/Commands.php  tho I did do a sync some days ago so it should have been in there already.

Thanks for the fix tho, maybe GH was just being odd and it didn't pick it up from the outset :-)

**Comment by helgi** [comment]
Oh, damn, I looked at this the wrong way around... You want to change it back to PEAR2_Pyrus_Developer; Sorry!  Why do you want to do that? I see no reason for the package to be still named PEAR2_ as Pyrus offers migration between packages and channels even (at least last I knew)

**Comment by Tyrael** [comment]
I didn't know that we are in the process of renaming the package.
After the pull request, I talked with @saltybeagle and he explained this.
I still think, that it would be good to have this fixed(not necessarily via changing back the package name), until the naming/packaging stuff gets sorted out.

**Comment by saltybeagle** [comment]
The naming has finally settled. Packages will be released on pyrus.net. Pyrus is the new vendor name, so packages related to the installer and channel infrastructure will be renamed to Pyrus_XXXXXXX.

I'll handle the updates for the channel name changes.

**Pull request closed without merging**
